name: "Continuous Integration"
on:
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - run: |
        dotnet build src/bsonkit.csproj
      name: Build BsonKit
    # TODO: testing here.
